##===- clang/lib/StaticAnalyzer/Makefile -------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
# This implements analyses built on top of source-level CFGs. 
#
##===----------------------------------------------------------------------===##

CLANG_LEVEL := ../..
PARALLEL_DIRS := Core Checkers Frontend

include $(CLANG_LEVEL)/Makefile
