#define yy_create_buffer llvmAsm_create_buffer
#define yy_delete_buffer llvmAsm_delete_buffer
#define yy_scan_buffer llvmAsm_scan_buffer
#define yy_scan_string llvmAsm_scan_string
#define yy_scan_bytes llvmAsm_scan_bytes
#define yy_flex_debug llvmAsm_flex_debug
#define yy_init_buffer llvmAsm_init_buffer
#define yy_flush_buffer llvmAsm_flush_buffer
#define yy_load_buffer_state llvmAsm_load_buffer_state
#define yy_switch_to_buffer llvmAsm_switch_to_buffer
#define yyin llvmAsmin
#define yyleng llvmAsmleng
#define yylex llvmAsmlex
#define yyout llvmAsmout
#define yyrestart llvmAsmrestart
#define yytext llvmAsmtext
#define yylineno llvmAsmlineno

#line 20 "Lexer.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE (16384*64)

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static inline void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 118
#define YY_END_OF_BUFFER 119
static yyconst short int yy_acclist[196] =
    {   0,
      119,  117,  118,  116,  117,  118,  116,  118,  117,  118,
      117,  118,  117,  118,  117,  118,  117,  118,  117,  118,
      109,  117,  118,  109,  117,  118,    1,  117,  118,  117,
      118,  117,  118,  117,  118,  117,  118,  117,  118,  117,
      118,  117,  118,  117,  118,  117,  118,  117,  118,  117,
      118,  117,  118,  117,  118,  117,  118,  117,  118,  117,
      118,  117,  118,  117,  118,  117,  118,  117,  118,  117,
      118,  108,  106,  105,  105,  112,  110,  114,  109,    1,
       85,   35,  104,   60,   20,  108,  105,  105,  113,  114,
       17,  114,  115,   54,   59,   30,   36,   57,    3,   45,

       56,   22,   74,   58,   84,   79,   80,   55,   61,  107,
      114,  114,   40,   75,   76,   92,   93,   47,   19,  111,
       23,    4,   52,   46,   97,   39,   11,  114,   33,    2,
        5,   32,   49,   51,   41,   63,   67,   65,   66,   64,
       62,   43,   94,   42,   48,   18,   82,   91,   38,   50,
       27,   21,   37,    7,   87,   29,   90,   53,   77,   86,
       24,   25,   88,   44,   83,   81,  103,   69,   73,   71,
       72,   70,   68,  101,    6,   26,   99,   34,   96,   78,
        8,   14,    9,   10,   31,   98,   12,   28,   89,   95,
       13,  102,  100,   15,   16

    } ;

static yyconst short int yy_accept[471] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   11,   13,   15,
       17,   19,   21,   24,   27,   30,   32,   34,   36,   38,
       40,   42,   44,   46,   48,   50,   52,   54,   56,   58,
       60,   62,   64,   66,   68,   70,   72,   72,   73,   73,
       74,   75,   76,   77,   77,   78,   78,   79,   80,   80,
       81,   81,   81,   81,   81,   81,   81,   81,   82,   82,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   84,   84,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   86,   86,   86,   86,

       86,   86,   86,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   87,   88,   90,   91,   92,   93,   93,
       94,   95,   95,   95,   96,   96,   96,   97,   97,   97,
       97,   98,   98,   98,   98,   98,   98,   99,   99,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      101,  101,  101,  101,  101,  101,  101,  101,  102,  103,
      103,  103,  104,  104,  105,  106,  106,  106,  106,  106,
      106,  107,  107,  108,  108,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,

      109,  110,  110,  111,  112,  112,  112,  112,  113,  113,
      113,  113,  113,  114,  115,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  118,
      119,  119,  120,  120,  120,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  122,  122,  122,  123,
      124,  124,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  126,  127,  127,  127,  127,  127,
      128,  128,  129,  130,  130,  130,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  132,  132,  133,

      134,  134,  134,  134,  134,  134,  135,  135,  135,  135,
      135,  135,  136,  136,  136,  137,  138,  139,  140,  141,
      142,  143,  144,  144,  144,  144,  145,  146,  147,  147,
      147,  147,  147,  147,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  149,  149,  150,  150,
      150,  150,  150,  151,  152,  153,  153,  153,  154,  154,
      155,  155,  155,  156,  156,  157,  158,  159,  159,  159,
      160,  161,  162,  163,  163,  163,  164,  165,  166,  167,
      168,  168,  168,  168,  168,  169,  170,  171,  172,  173,
      174,  174,  174,  175,  175,  176,  177,  177,  178,  178,

      178,  178,  178,  178,  179,  179,  179,  180,  180,  180,
      181,  181,  181,  181,  182,  183,  183,  183,  183,  184,
      185,  185,  185,  185,  186,  187,  187,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  188,  188,
      188,  188,  188,  188,  188,  188,  188,  188,  189,  189,
      190,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      191,  191,  192,  192,  193,  194,  195,  195,  196,  196
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    5,    6,    1,    1,    1,
        1,    1,    7,    1,    8,    9,    1,   10,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,   13,    1,
        1,    1,    1,    1,   14,   14,   14,   14,   15,   14,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1,    1,   16,    1,   17,   18,   19,   20,

       21,   22,   23,   24,   25,    5,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[42] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    3,    3,    3,
        3,    4,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3
    } ;

static yyconst short int yy_base[475] =
    {   0,
        0,    0,  980,  981,  981,  981,  975,  966,   34,   36,
       38,   42,   46,   50,    0,   51,   54,   53,   56,   61,
       76,   77,   79,   80,   82,   83,   84,   90,   31,  111,
      110,  141,  164,   55,  100,  104,  973,  981,  964,  981,
        0,  123,  126,  145,  151,  119,  162,  181,  189,    0,
      132,   99,  145,  127,   41,  155,  152,  963,  168,  126,
      185,  203,  159,  193,  204,  206,  205,  130,  207,  167,
      208,  214,  209,  211,  215,  216,  218,  226,  230,  219,
      237,  962,   57,  961,  238,  240,  243,  244,  246,  247,
      257,  249,  250,  248,  255,  960,  260,  258,  263,  264,

      265,  279,  282,  285,  129,  288,  280,  286,  297,  298,
      295,  307,  959,    0,  310,  312,  958,  314,  331,    0,
      957,  322,  318,  956,  325,  319,  955,  320,  324,  337,
      954,  338,  341,  340,  342,  343,  953,  344,  348,  345,
      355,  349,  351,  356,  363,  366,  369,  353,  352,  370,
      372,  373,  377,  380,  381,  383,  384,  952,  951,  385,
      386,  950,  387,  949,  948,  409,  397,  398,  392,  413,
      947,  388,  946,  402,  945,  410,  425,  426,  427,  396,
      429,  431,  432,  434,  435,  436,  439,  443,  441,  442,
      445,  449,  450,  452,  460,  457,  462,  463,  464,  469,

      944,  470,  981,  482,  494,  473,  496,  499,  461,  477,
      486,  500,  943,  942,  941,  501,  502,  482,  504,  506,
      507,  511,  510,  512,  513,  514,  520,  524,  521,  940,
      525,  526,  528,  530,  534,  535,  536,  538,  939,  938,
      539,  937,  541,  543,    0,  546,  545,  542,  547,  552,
      559,  560,  556,  562,  563,  936,  564,  572,  935,  934,
      574,  933,  577,  576,  578,  580,  581,  584,  589,  590,
      592,  593,  594,  932,  931,  595,  597,  599,  612,  930,
      596,  604,  929,  617,  607,  928,  624,  613,  628,  604,
      626,  634,  635,  614,  636,  638,  927,  639,  926,  925,

      640,  641,  600,  642,  648,  924,  644,  651,  647,  655,
      658,  923,  650,  662,  922,  921,  920,  919,  918,  917,
      916,  915,  663,  665,  669,  914,  913,  912,  666,  670,
      671,  672,  673,  911,  674,  680,  681,  683,  676,  686,
      682,  691,  694,  698,  687,  910,  692,  909,  706,  708,
      709,  710,  908,  907,  906,  711,  712,  905,  713,  904,
      719,  721,  903,  720,  902,  901,  900,  722,  723,  899,
      898,  897,  896,  724,  730,  895,  894,  893,  892,  891,
      731,  733,  736,  734,  890,  889,  888,  887,  886,  885,
      738,  739,  741,  744,  884,  883,  746,  749,  753,  747,

      754,  759,  755,  880,  760,  766,  871,  763,  770,  869,
      773,  774,  775,  868,  865,  778,  780,  776,  864,  862,
      779,  783,  781,  861,  860,  782,  856,  794,  800,  784,
      801,  786,  789,  804,  805,  808,  811,  812,  813,  814,
      788,  816,  818,  820,  821,  822,  826,  855,  828,  854,
      834,  832,  835,  838,  840,  842,  841,  843,  844,  853,
      846,  474,  848,  395,  393,  269,  851,  224,  981,  884,
      886,  183,  890,  181
    } ;

static yyconst short int yy_def[475] =
    {   0,
      469,    1,  469,  469,  469,  469,  470,  471,  472,  469,
      471,  471,  471,  471,  473,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  470,  469,  471,  469,
      474,  474,  469,  469,  471,  471,  471,  471,  471,  473,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  469,  474,  474,  469,  471,  471,  471,   49,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,   49,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  469,  469,  469,  469,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  166,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  469,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,    0,  469,
      469,  469,  469,  469
    } ;

static yyconst short int yy_nxt[1023] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,    4,   15,    8,    8,    8,   16,   17,   18,   19,
       20,   21,   22,    8,   23,    8,   24,   25,   26,   27,
       28,    8,   29,   30,   31,   32,   33,   34,   35,    8,
       36,   42,   40,   43,   43,   44,   44,   45,   45,   40,
       46,   87,   40,   40,   47,   48,   48,   40,   47,   48,
       48,   40,   40,  126,   40,   40,   40,   40,   40,   59,
       51,   60,   40,  161,   55,  110,   62,   52,   56,   53,
       63,   54,   61,   57,   49,   64,   58,   40,   40,   65,
       40,   40,   67,   40,   40,   40,   75,   71,   78,   66,

       68,   40,   69,   72,   76,   82,   73,   74,   70,   77,
       40,   40,   80,   85,   83,   40,   84,   79,   81,   86,
       88,   40,   40,  122,  112,  123,   95,  117,   89,  111,
       40,   90,  115,  115,   91,   43,   43,   40,   40,   96,
       40,   40,   97,   40,  131,   92,   93,  193,   94,   98,
       88,  121,   40,  116,   44,   44,   40,  125,   99,   47,
       45,   45,   40,   40,  124,  100,   40,  101,  144,  102,
       40,  118,  118,   40,  103,   40,  119,  127,   40,   40,
      104,  128,  119,  114,  105,   41,  106,  146,  107,   47,
       48,   48,   40,  108,  129,  137,   40,  109,  120,  120,

       40,  130,  120,  120,   40,  120,  120,  120,  120,  120,
      120,  132,  133,  134,   40,   40,   40,   40,   40,   40,
       40,  135,   40,  139,  140,   40,   40,   40,  138,   40,
       40,  142,  152,  136,  155,   40,  145,   40,  143,  149,
      141,   40,  147,  148,  153,  150,  156,  151,   40,   40,
      154,   40,  157,  159,   40,   40,  158,   40,   40,   40,
       40,   40,  162,  160,  163,  168,   40,  175,   40,   40,
      164,   40,  176,  169,   40,   40,   40,  165,  174,  177,
       40,  170,  166,  171,  179,  167,  172,  178,  181,  173,
       40,   40,  183,   40,  184,  180,   40,   40,  185,   40,

      190,  191,  182,  186,  194,  189,   40,  195,   40,   40,
      196,  187,  197,  192,  200,  198,  188,  199,   40,  115,
      115,  204,  204,  118,  118,   40,  205,  201,  119,   40,
       40,   40,  205,   40,  119,   40,   40,  206,  207,  202,
      208,  208,   40,  212,  209,  211,  213,  210,   40,   40,
      214,   40,   40,   40,   40,   40,   40,  216,  217,   40,
       40,  221,   40,   40,   40,  223,   40,   40,  219,  220,
      232,  215,  222,  218,   40,  224,  228,   40,  233,  229,
       40,   40,  226,   40,   40,  227,  230,  225,   40,  231,
      234,   40,   40,  236,   40,   40,   40,   40,   40,   40,

      239,  235,  237,   40,   40,  240,   40,   40,   40,   40,
      241,  242,  248,   40,  238,  244,  259,  243,  245,  245,
      253,   40,  245,  245,   40,  245,  245,  245,  245,  245,
      245,  246,  247,  249,  254,  250,   40,   40,   40,  251,
       40,  252,   40,   40,  255,   40,   40,   40,  257,  260,
       40,  256,   40,   40,   40,  264,   40,  258,  269,  266,
       40,   40,  263,   40,  265,  261,  262,  267,   40,  271,
      268,   40,   40,   40,   40,   40,  275,  270,  276,  277,
       40,   40,  282,  282,  272,   40,  273,  274,   40,  283,
      278,  204,  204,   40,  280,  284,  205,   40,  279,  281,

      206,  206,  205,  282,  282,  208,  208,   40,  208,  208,
       40,   40,   40,   40,  285,   40,  289,   40,   40,  287,
      290,   40,   40,   40,   40,   40,  288,  293,  286,  296,
      291,   40,   40,  292,  297,   40,   40,   40,  298,   40,
      294,   40,  302,  299,  295,   40,   40,   40,  303,   40,
       40,  301,   40,   40,   40,  300,   40,   40,   40,  305,
      314,  306,  304,   40,  308,  307,  312,   40,  309,  313,
       40,   40,  316,   40,   40,   40,  310,  311,  315,  318,
      320,  323,  322,   40,  324,   40,  317,   40,   40,   40,
      321,   40,   40,  319,  326,   40,  330,  328,  325,  327,

       40,   40,  329,   40,   40,   40,   40,   40,   40,  331,
       40,   40,  334,  282,  282,   40,  332,  337,   40,  340,
      345,  333,  336,   40,   40,   40,  347,  361,   40,  338,
      335,  339,  341,  346,  342,   40,  351,   40,  343,   40,
      344,  349,  348,  352,  350,   40,   40,   40,  355,   40,
       40,   40,   40,   40,  353,   40,  357,  358,   40,   40,
      359,   40,   40,  354,  356,  366,   40,  360,  363,   40,
      362,  365,  364,   40,   40,  367,   40,   40,  368,  369,
       40,   40,   40,   40,   40,   40,  371,   40,  375,  373,
      376,   40,   40,   40,   40,  378,  370,   40,   40,  372,

      374,  381,   40,   40,  384,   40,  377,  382,  379,   40,
      383,  386,  380,  385,  388,  391,  392,   40,  390,   40,
       40,   40,   40,   40,   40,  387,  393,  397,  389,  395,
       40,   40,   40,   40,   40,   40,  394,  401,  402,  400,
      399,   40,   40,  396,   40,   40,  398,   40,  405,   40,
       40,  404,   40,  406,  403,   40,  409,   40,   40,  408,
       40,  413,  411,  407,   40,   40,   40,  412,  410,  416,
       40,   40,  415,  417,   40,  418,  422,   40,  414,  420,
      419,   40,  423,  424,   40,   40,   40,   40,  421,   40,
       40,   40,   40,   40,   40,   40,  427,   40,  434,   40,

       40,  428,  425,  432,  429,   40,  435,  426,  430,  433,
      431,   40,   40,  441,  436,   40,   40,  439,  438,   40,
      437,  443,   40,   40,   40,   40,  440,   40,  449,   40,
      442,   40,   40,   40,  448,  444,  450,   40,  445,   40,
      452,  453,  446,   40,  451,   40,   40,  447,  456,   40,
      455,   40,   40,   40,   40,   40,  454,   40,  457,   40,
      458,  462,   40,  459,   40,   40,   40,   40,  467,  461,
      460,   40,   40,   40,  466,   40,   40,  464,  465,   40,
       40,  463,   40,  468,   37,   37,   37,   37,   39,   39,
       50,   40,   50,   50,   40,   40,   40,   40,   40,   40,

       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
      203,   40,   40,   40,   40,   40,  113,   40,   38,  469,
        3,  469,  469,  469,  469,  469,  469,  469,  469,  469,
      469,  469,  469,  469,  469,  469,  469,  469,  469,  469,

      469,  469,  469,  469,  469,  469,  469,  469,  469,  469,
      469,  469,  469,  469,  469,  469,  469,  469,  469,  469,
      469,  469
    } ;

static yyconst short int yy_chk[1023] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,   29,    9,    9,   10,   10,   11,   11,   11,
       12,   29,   55,   12,   13,   13,   13,   13,   14,   14,
       14,   14,   16,   55,   18,   17,   34,   19,   83,   18,
       16,   18,   20,   83,   17,   34,   19,   16,   17,   16,
       19,   16,   18,   17,   13,   19,   17,   21,   22,   20,
       23,   24,   21,   25,   26,   27,   24,   22,   25,   20,

       21,   28,   21,   22,   24,   27,   23,   23,   21,   24,
       52,   35,   26,   28,   27,   36,   27,   25,   26,   28,
       30,   31,   30,   52,   36,   52,   31,   46,   30,   35,
       46,   30,   42,   42,   30,   43,   43,   60,   54,   31,
      105,   68,   31,   51,   60,   30,   30,  105,   30,   31,
       32,   51,   32,   44,   44,   44,   53,   54,   32,   45,
       45,   45,   45,   57,   53,   32,   56,   32,   68,   32,
       63,   47,   47,   47,   32,   33,   47,   56,   70,   59,
       33,   57,   47,  474,   33,  472,   33,   70,   33,   48,
       48,   48,   48,   33,   59,   63,   61,   33,   49,   49,

       49,   59,   49,   49,   64,   49,   49,   49,   49,   49,
       49,   61,   61,   61,   62,   65,   67,   66,   69,   71,
       73,   62,   74,   65,   66,   72,   75,   76,   64,   77,
       80,   67,   75,   62,   77,  468,   69,   78,   67,   73,
       66,   79,   71,   72,   76,   74,   77,   74,   81,   85,
       76,   86,   78,   80,   87,   88,   79,   89,   90,   94,
       92,   93,   85,   81,   86,   90,   95,   93,   91,   98,
       87,   97,   94,   90,   99,  100,  101,   87,   92,   95,
      466,   90,   88,   91,   97,   89,   91,   95,   98,   91,
      102,  107,  100,  103,  101,   97,  104,  108,  102,  106,

      104,  104,   99,  102,  106,  103,  111,  107,  109,  110,
      108,  102,  108,  104,  110,  109,  102,  109,  112,  115,
      115,  116,  116,  118,  118,  118,  116,  111,  118,  123,
      126,  128,  116,  122,  118,  129,  125,  119,  119,  112,
      119,  119,  119,  126,  122,  125,  128,  123,  130,  132,
      129,  134,  133,  135,  136,  138,  140,  132,  133,  139,
      142,  138,  143,  149,  148,  140,  141,  144,  135,  136,
      148,  130,  139,  134,  145,  141,  144,  146,  149,  145,
      147,  150,  142,  151,  152,  143,  146,  141,  153,  147,
      150,  154,  155,  152,  156,  157,  160,  161,  163,  172,

      155,  151,  153,  169,  465,  156,  464,  180,  167,  168,
      157,  160,  169,  174,  154,  163,  180,  161,  166,  166,
      172,  176,  166,  166,  170,  166,  166,  166,  166,  166,
      166,  167,  168,  170,  174,  170,  177,  178,  179,  170,
      181,  170,  182,  183,  176,  184,  185,  186,  178,  181,
      187,  177,  189,  190,  188,  185,  191,  179,  190,  187,
      192,  193,  184,  194,  186,  182,  183,  188,  196,  192,
      189,  195,  209,  197,  198,  199,  196,  191,  197,  198,
      200,  202,  206,  206,  193,  462,  194,  195,  210,  209,
      199,  204,  204,  218,  200,  210,  204,  211,  199,  202,

      205,  205,  204,  205,  205,  207,  207,  207,  208,  208,
      208,  212,  216,  217,  211,  219,  218,  220,  221,  216,
      219,  223,  222,  224,  225,  226,  217,  222,  212,  225,
      220,  227,  229,  221,  226,  228,  231,  232,  227,  233,
      223,  234,  232,  228,  224,  235,  236,  237,  233,  238,
      241,  231,  243,  248,  244,  229,  247,  246,  249,  235,
      248,  236,  234,  250,  238,  237,  246,  253,  241,  247,
      251,  252,  250,  254,  255,  257,  243,  244,  249,  251,
      252,  255,  254,  258,  257,  261,  250,  264,  263,  265,
      253,  266,  267,  251,  261,  268,  266,  264,  258,  263,

      269,  270,  265,  271,  272,  273,  276,  281,  277,  267,
      278,  303,  270,  282,  282,  290,  268,  273,  285,  278,
      281,  269,  272,  279,  288,  294,  285,  303,  284,  276,
      271,  277,  279,  284,  279,  287,  290,  291,  279,  289,
      279,  288,  287,  291,  289,  292,  293,  295,  294,  296,
      298,  301,  302,  304,  292,  307,  296,  298,  309,  305,
      301,  313,  308,  293,  295,  309,  310,  302,  305,  311,
      304,  308,  307,  314,  323,  310,  324,  329,  311,  313,
      325,  330,  331,  332,  333,  335,  323,  339,  330,  325,
      331,  336,  337,  341,  338,  333,  314,  340,  345,  324,

      329,  337,  342,  347,  340,  343,  332,  338,  335,  344,
      339,  342,  336,  341,  343,  345,  347,  349,  344,  350,
      351,  352,  356,  357,  359,  342,  349,  356,  343,  351,
      361,  364,  362,  368,  369,  374,  350,  362,  364,  361,
      359,  375,  381,  352,  382,  384,  357,  383,  374,  391,
      392,  369,  393,  375,  368,  394,  383,  397,  400,  382,
      398,  393,  391,  381,  399,  401,  403,  392,  384,  398,
      402,  405,  397,  399,  408,  400,  405,  406,  394,  402,
      401,  409,  406,  408,  411,  412,  413,  418,  403,  416,
      421,  417,  423,  426,  422,  430,  412,  432,  423,  441,

      433,  413,  409,  421,  416,  428,  426,  411,  417,  422,
      418,  429,  431,  433,  428,  434,  435,  431,  430,  436,
      429,  435,  437,  438,  439,  440,  432,  442,  441,  443,
      434,  444,  445,  446,  440,  436,  442,  447,  437,  449,
      444,  445,  438,  452,  443,  451,  453,  439,  449,  454,
      447,  455,  457,  456,  458,  459,  446,  461,  451,  463,
      452,  456,  467,  453,  460,  450,  448,  427,  463,  455,
      454,  425,  424,  420,  461,  419,  415,  458,  459,  414,
      410,  457,  407,  467,  470,  470,  470,  470,  471,  471,
      473,  404,  473,  473,  396,  395,  390,  389,  388,  387,

      386,  385,  380,  379,  378,  377,  376,  373,  372,  371,
      370,  367,  366,  365,  363,  360,  358,  355,  354,  353,
      348,  346,  334,  328,  327,  326,  322,  321,  320,  319,
      318,  317,  316,  315,  312,  306,  300,  299,  297,  286,
      283,  280,  275,  274,  262,  260,  259,  256,  242,  240,
      239,  230,  215,  214,  213,  201,  175,  173,  171,  165,
      164,  162,  159,  158,  137,  131,  127,  124,  121,  117,
      113,   96,   84,   82,   58,   39,   37,    8,    7,    3,
      469,  469,  469,  469,  469,  469,  469,  469,  469,  469,
      469,  469,  469,  469,  469,  469,  469,  469,  469,  469,

      469,  469,  469,  469,  469,  469,  469,  469,  469,  469,
      469,  469,  469,  469,  469,  469,  469,  469,  469,  469,
      469,  469
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
#define INITIAL 0
/*===-- Lexer.l - Scanner for llvm assembly files --------------*- C++ -*--===//
//
//                     The LLVM Compiler Infrastructure
//
// This file was developed by the LLVM research group and is distributed under
// the University of Illinois Open Source License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
//  This file implements the flex scanner for LLVM assembly languages files.
//
//===----------------------------------------------------------------------===*/
#define YY_NEVER_INTERACTIVE 1
#line 28 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
#include "ParserInternals.h"
#include "llvm/Module.h"
#include <list>
#include "llvmAsmParser.h"
#include <cctype>
#include <cstdlib>

void set_scan_file(FILE * F){
  yy_switch_to_buffer(yy_create_buffer( F, YY_BUF_SIZE ) );
}
void set_scan_string (const char * str) {
  yy_scan_string (str);
}

#define RET_TOK(type, Enum, sym) \
  llvmAsmlval.type = Instruction::Enum; return sym

namespace llvm {

// TODO: All of the static identifiers are figured out by the lexer,
// these should be hashed to reduce the lexer size


// atoull - Convert an ascii string of decimal digits into the unsigned long
// long representation... this does not have to do input error checking,
// because we know that the input will be matched by a suitable regex...
//
static uint64_t atoull(const char *Buffer) {
  uint64_t Result = 0;
  for (; *Buffer; Buffer++) {
    uint64_t OldRes = Result;
    Result *= 10;
    Result += *Buffer-'0';
    if (Result < OldRes)   // Uh, oh, overflow detected!!!
      ThrowException("constant bigger than 64 bits detected!");
  }
  return Result;
}

static uint64_t HexIntToVal(const char *Buffer) {
  uint64_t Result = 0;
  for (; *Buffer; ++Buffer) {
    uint64_t OldRes = Result;
    Result *= 16;
    char C = *Buffer;
    if (C >= '0' && C <= '9')
      Result += C-'0';
    else if (C >= 'A' && C <= 'F')
      Result += C-'A'+10;
    else if (C >= 'a' && C <= 'f')
      Result += C-'a'+10;

    if (Result < OldRes)   // Uh, oh, overflow detected!!!
      ThrowException("constant bigger than 64 bits detected!");
  }
  return Result;
}


// HexToFP - Convert the ascii string in hexidecimal format to the floating
// point representation of it.
//
static double HexToFP(const char *Buffer) {
  // Behave nicely in the face of C TBAA rules... see:
  // http://www.nullstone.com/htmls/category/aliastyp.htm
  union {
    uint64_t UI;
    double FP;
  } UIntToFP;
  UIntToFP.UI = HexIntToVal(Buffer);

  assert(sizeof(double) == sizeof(uint64_t) &&
         "Data sizes incompatible on this target!");
  return UIntToFP.FP;   // Cast Hex constant to double
}


// UnEscapeLexed - Run through the specified buffer and change \xx codes to the
// appropriate character.  If AllowNull is set to false, a \00 value will cause
// an exception to be thrown.
//
// If AllowNull is set to true, the return value of the function points to the
// last character of the string in memory.
//
char *UnEscapeLexed(char *Buffer, bool AllowNull) {
  char *BOut = Buffer;
  for (char *BIn = Buffer; *BIn; ) {
    if (BIn[0] == '\\' && isxdigit(BIn[1]) && isxdigit(BIn[2])) {
      char Tmp = BIn[3]; BIn[3] = 0;     // Terminate string
      *BOut = (char)strtol(BIn+1, 0, 16);  // Convert to number
      if (!AllowNull && !*BOut)
        ThrowException("String literal cannot accept \\00 escape!");

      BIn[3] = Tmp;                  // Restore character
      BIn += 3;                      // Skip over handled chars
      ++BOut;
    } else {
      *BOut++ = *BIn++;
    }
  }

  return BOut;
}

} // End llvm namespace

using namespace llvm;

#define YY_NEVER_INTERACTIVE 1
/* Comments start with a ; and go till end of line */
/* Variable(Value) identifiers start with a % sign */
/* Label identifiers end with a colon */
/* Quoted names can contain any character except " and \ */
/* [PN]Integer: match positive and negative literal integer values that
 * are preceeded by a '%' character.  These represent unnamed variable slots.
 */
/* E[PN]Integer: match positive and negative literal integer values */
/* FPConstant - A Floating point constant.
 */
/* HexFPConstant - Floating point constant represented in IEEE format as a
 *  hexadecimal number for when exponential notation is not precise enough.
 */
/* HexIntConstant - Hexadecimal constant generated by the CFE to avoid forcing
 * it to deal with 64 bit numbers.
 */
#line 937 "Lexer.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static inline void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 179 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"


#line 1091 "Lexer.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 470 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_current_state != 469 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 181 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ /* Ignore comments for now */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 183 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return BEGINTOK; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 184 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return ENDTOK; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 185 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return TRUETOK;  }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 186 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return FALSETOK; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 187 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return DECLARE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 188 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return GLOBAL; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 189 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return CONSTANT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 190 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return INTERNAL; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 191 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return LINKONCE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 192 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return WEAK; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 193 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return APPENDING; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 194 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return EXTERNAL; }    /* Deprecated, turn into external */
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 195 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return EXTERNAL; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 196 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return IMPLEMENTATION; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 197 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return ZEROINITIALIZER; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 198 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return DOTDOTDOT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 199 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return UNDEF; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 200 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return NULL_TOK; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 201 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return TO; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 202 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(TermOpVal, Unwind, UNWIND); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 203 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return NOT; }  /* Deprecated, turned into XOR */
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 204 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return TAIL; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 205 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return TARGET; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 206 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return TRIPLE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 207 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return DEPLIBS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 208 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return ENDIAN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 209 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return POINTERSIZE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 210 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return LITTLE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 211 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return BIG; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 212 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return VOLATILE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 213 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return FIXED; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 214 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return ALIGN;  }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 215 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return SECTION; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 217 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return CC_TOK; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 218 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return CCC_TOK; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 219 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return FASTCC_TOK; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 220 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return COLDCC_TOK; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 222 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.PrimType = Type::VoidTy  ; return VOID;   }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 223 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.PrimType = Type::BoolTy  ; return BOOL;   }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 224 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.PrimType = Type::SByteTy ; return SBYTE;  }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 225 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.PrimType = Type::UByteTy ; return UBYTE;  }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 226 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.PrimType = Type::ShortTy ; return SHORT;  }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 227 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.PrimType = Type::UShortTy; return USHORT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 228 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.PrimType = Type::IntTy   ; return INT;    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 229 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.PrimType = Type::UIntTy  ; return UINT;   }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 230 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.PrimType = Type::LongTy  ; return LONG;   }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 231 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.PrimType = Type::ULongTy ; return ULONG;  }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 232 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.PrimType = Type::FloatTy ; return FLOAT;  }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 233 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.PrimType = Type::DoubleTy; return DOUBLE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 234 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.PrimType = Type::LabelTy ; return LABEL;  }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 235 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return TYPE;   }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 236 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return OPAQUE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 238 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, Add, ADD); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 239 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, Sub, SUB); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 240 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, Mul, MUL); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 241 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, Div, DIV); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 242 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, Rem, REM); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 243 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, And, AND); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 244 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, Or , OR ); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 245 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, Xor, XOR); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 246 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, SetNE, SETNE); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 247 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, SetEQ, SETEQ); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 248 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, SetLT, SETLT); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 249 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, SetGT, SETGT); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 250 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, SetLE, SETLE); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 251 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, SetGE, SETGE); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 252 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, VSetNE, VSETNE); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 253 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, VSetEQ, VSETEQ); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 254 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, VSetLT, VSETLT); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 255 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, VSetGT, VSETGT); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 256 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, VSetLE, VSETLE); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 257 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(BinaryOpVal, VSetGE, VSETGE); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 259 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(OtherOpVal, PHI, PHI_TOK); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 260 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(OtherOpVal, Call, CALL); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 261 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(OtherOpVal, Cast, CAST); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 262 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(OtherOpVal, Select, SELECT); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 263 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(OtherOpVal, VSelect, VSELECT); } 
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 264 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(OtherOpVal, Shl, SHL); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 265 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(OtherOpVal, Shr, SHR); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 266 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return VANEXT_old; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 267 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return VAARG_old; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 268 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(OtherOpVal, VAArg , VAARG); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 269 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(TermOpVal, Ret, RET); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 270 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(TermOpVal, Br, BR); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 271 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(TermOpVal, Switch, SWITCH); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 272 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(TermOpVal, Invoke, INVOKE); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 273 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(TermOpVal, Unwind, UNWIND); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 274 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(TermOpVal, Unreachable, UNREACHABLE); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 276 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(MemOpVal, Malloc, MALLOC); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 277 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(MemOpVal, Alloca, ALLOCA); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 278 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(MemOpVal, Free, FREE); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 279 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(MemOpVal, Load, LOAD); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 280 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(MemOpVal, Store, STORE); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 281 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(MemOpVal, GetElementPtr, GETELEMENTPTR); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 282 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(MemOpVal, VGather, VGATHER); } 
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 283 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(MemOpVal, VImm, VIMM); } 
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 284 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(MemOpVal, VScatter, VSCATTER); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 286 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(OtherOpVal, Extract, EXTRACT); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 287 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(OtherOpVal, ExtractElement, EXTRACTELEMENT); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 288 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(OtherOpVal, Combine, COMBINE); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 289 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ RET_TOK(OtherOpVal, CombineElement, COMBINEELEMENT); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 290 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return VECTOR; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 291 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return OF; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 293 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{
                  UnEscapeLexed(yytext+1);
                  llvmAsmlval.StrVal = strdup(yytext+1);             // Skip %
                  return VAR_ID;
                }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 298 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{
                  yytext[strlen(yytext)-1] = 0;  // nuke colon
                  UnEscapeLexed(yytext);
                  llvmAsmlval.StrVal = strdup(yytext);
                  return LABELSTR;
                }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 304 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{
                  yytext[strlen(yytext)-2] = 0;  // nuke colon, end quote
                  UnEscapeLexed(yytext+1);
                  llvmAsmlval.StrVal = strdup(yytext+1);
                  return LABELSTR;
                }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 311 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ // Note that we cannot unescape a string constant here!  The
                   // string constant might contain a \00 which would not be
                   // understood by the string stuff.  It is valid to make a
                   // [sbyte] c"Hello World\00" constant, for example.
                   //
                   yytext[strlen(yytext)-1] = 0;           // nuke end quote
                   llvmAsmlval.StrVal = strdup(yytext+1);  // Nuke start quote
                   return STRINGCONSTANT;
                 }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 322 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.UInt64Val = atoull(yytext); return EUINT64VAL; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 323 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{
                  uint64_t Val = atoull(yytext+1);
                  // +1:  we have bigger negative range
                  if (Val > (uint64_t)INT64_MAX+1)
                    ThrowException("Constant too large for signed 64 bits!");
                  llvmAsmlval.SInt64Val = -Val;
                  return ESINT64VAL;
                }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 331 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{
                   llvmAsmlval.UInt64Val = HexIntToVal(yytext+3);
                   return yytext[0] == 's' ? ESINT64VAL : EUINT64VAL;
                 }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 336 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{
                  uint64_t Val = atoull(yytext+1);
                  if ((unsigned)Val != Val)
                    ThrowException("Invalid value number (too large)!");
                  llvmAsmlval.UIntVal = unsigned(Val);
                  return UINTVAL;
                }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 343 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{
                  uint64_t Val = atoull(yytext+2);
                  // +1:  we have bigger negative range
                  if (Val > (uint64_t)INT32_MAX+1)
                    ThrowException("Constant too large for signed 32 bits!");
                  llvmAsmlval.SIntVal = (int)-Val;
                  return SINTVAL;
                }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 352 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.FPVal = atof(yytext); return FPVAL; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 353 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ llvmAsmlval.FPVal = HexToFP(yytext); return FPVAL; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 355 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{
                  /* Make sure to free the internal buffers for flex when we are
                   * done reading our input!
                   */
                  yy_delete_buffer(YY_CURRENT_BUFFER);
                  return EOF;
                }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 363 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ /* Ignore whitespace */ }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 364 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
{ return yytext[0]; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 366 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1827 "Lexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 470 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 470 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 469);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static inline void yyunput( int c, register char *yy_bp )
#else
static inline void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static inline void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static inline void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 366 "/home/vadve/bocchino/llvm/src/lib/AsmParser/Lexer.l"

